sitename: DAZ Codes
breadcrumb_separator: "&raquo;"
breadcrumb_class: swifty_breadcrumb
link_class: swifty_link
tag_class: tag
max_image_size: 800
default_layout_name: site
default_link_name: links
turbo: true

dateFormat:
  weekday: short
  month: short
  day: numeric
  year: numeric

rss_feeds:
  - folder: blog
    title: DAZ codes Blog
    description: My thoughts about coding and anything else
